version: '3.4'
services:
  db:
    image: mysql
    container_name: db
    command: mysqld --user=root --verbose
    volumes:
      - ./dbcreation.sql:/tmp/dbcreation.sql
      - ./import.sh:/tmp/import.sh
    environment:
      MYSQL_DATABASE: "hotels"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user13690"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306

  backend:
    image: com.kunats.inc/hotels:latest
    container_name: backend-container
    restart: always
    mem_limit: 288m
    environment:
      - JVM_OPTIONS=-Xmx160m -XX:MaxMetaspaceSize=64m -XX:MaxRAM=288m
      - MYSQL_HOST=ecse00100b40.epam.com
      - MYSQL_PORT=3306
      - MYSQL_PWD=root
    ports:
      - 9090:8080

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/app