version: '2.3'
services:
  db:
    image: mysql
    container_name: database.dev
    command: mysqld --user=root --verbose
    volumes:
      - ./dbcreation.sql:/tmp/dbcreation.sql
      - ./import.sh:/tmp/import.sh
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "hotels"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user13690"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  backend:
    image: hotels/apphotel:latest
    container_name: backend-container
    restart: always
    mem_limit: 288m
    environment:
      - JVM_OPTIONS=-Xmx160m -XX:MaxMetaspaceSize=64m -XX:MaxRAM=288m
      - ORACLE_HOST=ecse00100b40.epam.com
      - ORACLE_PORT=8085
      - ORACLE_PWD=13693509
    ports:
      - 9090:80