version: '3.4'
services:
  db:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
    - postgres:/data/postgres
    ports:
    - 5432:5432
    networks:
    - postgres
    restart: unless-stopped

  backend:
    image: com.kunats.inc/hotels:latest
    container_name: backend-container
    restart: always
    environment:
      - JVM_OPTIONS=-Xmx160m -XX:MaxMetaspaceSize=64m -XX:MaxRAM=288m
      - MYSQL_HOST=ecse00100b40.epam.com
      - MYSQL_PORT=3306
      - MYSQL_PWD=root
    ports:
      - 9090:8080

  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    environment:
      - NODE_ENV=production
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/app